
package lostucanesdetijuana;

import javax.swing.JLabel;
import javax.swing.JTextArea;


public class ventaboletos extends javax.swing.JFrame {

  
    public ventaboletos() {
        initComponents();
    }   
     public JLabel getGrupo(){
        return grupo;
    }
     public JLabel getGrupo2(){
        return grupo2;
    }
     public JLabel getVenta(){
        return venta;
    }
     public JLabel getP1(){
        return puerta1;
    }
     public JLabel getP2(){
        return puerta2;
    }
     public JTextArea gerres(){
        return resultados;
    }
    public int contador;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taquilla = new javax.swing.JPanel();
        grupo = new javax.swing.JLabel();
        puerta1 = new javax.swing.JLabel();
        puerta2 = new javax.swing.JLabel();
        venta = new javax.swing.JLabel();
        grupo2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostucanesdetijuana/depositphotos_16268637-stock-photo-groups-of.jpg"))); // NOI18N

        puerta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostucanesdetijuana/GI-puerta-grande-madera-vidrios_1.jpg"))); // NOI18N

        puerta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostucanesdetijuana/GI-puerta-grande-madera-vidrios_1.jpg"))); // NOI18N

        venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostucanesdetijuana/personas-pie-cola-tienda_23-2148594615.jpg"))); // NOI18N

        grupo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostucanesdetijuana/depositphotos_16268637-stock-photo-groups-of.jpg"))); // NOI18N

        javax.swing.GroupLayout taquillaLayout = new javax.swing.GroupLayout(taquilla);
        taquilla.setLayout(taquillaLayout);
        taquillaLayout.setHorizontalGroup(
            taquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taquillaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(grupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(grupo2)
                .addGap(35, 35, 35))
            .addGroup(taquillaLayout.createSequentialGroup()
                .addGroup(taquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taquillaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(puerta1)
                        .addGap(68, 68, 68)
                        .addComponent(puerta2))
                    .addGroup(taquillaLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(venta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        taquillaLayout.setVerticalGroup(
            taquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taquillaLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(taquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puerta2)
                    .addComponent(puerta1))
                .addGap(18, 18, 18)
                .addComponent(venta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taquillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(taquillaLayout.createSequentialGroup()
                        .addComponent(grupo)
                        .addGap(8, 8, 8))
                    .addComponent(grupo2))
                .addGap(54, 54, 54))
        );

        jButton1.setText("INICIAR SIMULACION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        resultados.setColumns(20);
        resultados.setRows(5);
        jScrollPane1.setViewportView(resultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taquilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taquilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int camino_alea = (int)(Math.random()*2);
        int camino_alea2 = (int)(Math.random()*2);
        contador = 0;
        entrada1 hilo1 = new entrada1(grupo, camino_alea, this, grupo.getLocation().x, grupo.getLocation().y);
        entrada2 hilo2 = new entrada2(grupo2, camino_alea2, this, grupo2.getLocation().x, grupo2.getLocation().y);
        

        
        hilo1.start();
        hilo2.start();
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grupo;
    private javax.swing.JLabel grupo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel puerta1;
    private javax.swing.JLabel puerta2;
    private javax.swing.JTextArea resultados;
    private javax.swing.JPanel taquilla;
    private javax.swing.JLabel venta;
    // End of variables declaration//GEN-END:variables
}
